import '../models/items.dart';

class DummyItemProvider {
  static List<Items> getDummyItem() {
    return [
      Items(
        "",
        'assets/images/room1.webp',
        'Standard Room',
        1000,
        2,
        'No 1 Everest Heights, Lahore Pakistan',
        """Perfect for solo travelers or couples looking for comfort and simplicity. Equipped with a queen-size bed, smart TV, and Wi-Fi. Modern interiors with soft lighting and subtle tones. Ideal for short stays with all the essentials in place. Relax, recharge, and enjoy the cozy ambiance. Close to lobby and dining for convenience.""",
      ),
      Items(
        "",
        'assets/images/room2.webp',
        'Deluxe Room',
        2000,
        2,
        'No 2 Everest Heights, Lahore Pakistan',
        """Spacious and stylish with premium finishes. King-size bed, lounge chair, and elegant lighting. Balcony access with partial city views. Great for couples wanting a romantic stay. Includes minibar, high-speed Wi-Fi, and room service. Designed for comfort and a touch of luxury.""",
      ),
      Items(
        "",
        'assets/images/room3.webp',
        'Deluxe King',
        3000,
        3,
        'No 3 Everest Heights, Lahore Pakistan',
        """A step above the Deluxe, with extra space and elegance. Luxurious king bed, plush furnishings, and ambient lighting. Large window brings in natural light and stunning views. Perfect for a peaceful staycation or a work trip. Modern bathroom with walk-in shower and essentials. Smart controls for lighting, temp, and service.""",
      ),
      Items(
        "",
        'assets/images/room4.webp',
        'Executive Suit Room',
        4000,
        2,
        'No 4 Everest Heights, Lahore Pakistan',
        """Designed for business travelers and long stays. Separate work desk, lounge area, and high-end decor. Comfort meets class with curated interiors. Complimentary breakfast and executive access perks. Offers both productivity and relaxation zones. Make it your customerHome away from customerHome.""",
      ),
      Items(
        "",
        'assets/images/room5.webp',
        'Executive Royal Room',
        5000,
        4,
        'No 5 Everest Heights, Lahore Pakistan',
        """A royal retreat with stately ambiance and comfort. Lavish king bed, elegant seating, and modern luxury. Private balcony with panoramic city views. Ideal for elite guests or special occasions. Spacious enough for meetings or leisure. Unmatched style, comfort, and privacy.""",
      ),
      Items(
        "",
        'assets/images/room6.webp',
        'Family Suit',
        5500,
        3,
        'No 6 Everest Heights, Lahore Pakistan',
        """Your family’s comfort zone with multiple sleeping options. Two queen beds and a convertible sofa for flexibility. Kids and adults alike will love the cozy setup. Separate lounge space for bonding and games. Smart TV, snacks bar, and extra storage provided. Perfect for longer stays with the whole crew.""",
      ),
      Items(
        "",
        'assets/images/room7.webp',
        'Pent House',
        7000,
        7,
        'No 7 Everest Heights, Lahore Pakistan',
        """Luxury at the top with breathtaking views. Glass walls, private terrace, and chic interiors. Master bedroom plus entertainment space. Exclusive access to rooftop dining and hot tub. Perfect for celebrities, CEOs, or special events. Live the high life in this premium escape.""",
      ),
      Items(
        "",
        'assets/images/room8.jpg',
        'Serenity Room',
        4100,
        2,
        'No 8 Everest Heights, Lahore Pakistan',
        """As peaceful as the name sounds. Muted tones, soft lights, and calming vibes. Ideal for solo travelers or mindful getaways. Comes with reading nook and nature-inspired decor. Soothing view of gardens or courtyard. Recharge your mind and body in serenity.""",
      ),
      Items(
        "",
        'assets/images/room9.jpg',
        'Cozy Cove',
        3500,
        3,
        'No 9 Everest Heights, Lahore Pakistan',
        """Warm, intimate, and full of charm. Compact room with rich textures and soft bedding. Ideal for short getaways or remote work. Snuggle in with a book or binge your favorite show. Eco-friendly materials for a guilt-free stay. Great for digital nomads or romantic nights.""",
      ),
      Items(
        "",
        'assets/images/room10.jpg',
        'Pixel Room',
        2500,
        4,
        'No 10 Everest Heights, Lahore Pakistan',
        """A modern room with a digital edge. Tech-friendly space with mood lights and smart features. Futuristic decor with bold pops of color. Perfect for gamers, creatives, and Gen Z guests. Fast Wi-Fi, media dock, and cool ambient setup. Where style meets technology in comfort.""",
      ),
    ];
  }
}
