// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tu_PR34VjO1YEtEbzkPkfEstPlunWks',
    appId: '1:709341063423:web:a9130803b4cb8c9d1e84ca',
    messagingSenderId: '709341063423',
    projectId: 'everest-heights',
    authDomain: 'everest-heights.firebaseapp.com',
    storageBucket: 'everest-heights.firebasestorage.app',
    measurementId: 'G-48WSMK3TCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0q_OkOHgIdGUgErJDgWu19XJbaObnncU',
    appId: '1:709341063423:android:beeff3caaca43b641e84ca',
    messagingSenderId: '709341063423',
    projectId: 'everest-heights',
    storageBucket: 'everest-heights.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8ehqUPJSSueBmKtwIqiRSNT1N1omLn8',
    appId: '1:709341063423:ios:29b3f01ad65e36271e84ca',
    messagingSenderId: '709341063423',
    projectId: 'everest-heights',
    storageBucket: 'everest-heights.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
